### ISSUE TITLE
GET / returns HTTP 500

### ISSUE THREAD

**Issue by marcelklehr** [magpie-ea/magpie-backend#134]
```
web_1  | Server: localhost:4000 (http)
web_1  | Request: GET /
web_1  | ** (exit) an exception was raised:
web_1  |     ** (RuntimeError) expected basic_auth/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: nil
web_1  |         (magpie 2.0.4) Magpie.Router.browser/2
web_1  |         (magpie 2.0.4) lib/magpie_web/router.ex:1: Magpie.Router.__pipe_through0__/1
web_1  |         (phoenix 1.6.7) lib/phoenix/router.ex:347: Phoenix.Router.__call__/2
web_1  |         (magpie 2.0.4) lib/plug/error_handler.ex:80: Magpie.Router.call/2
web_1  |         (magpie 2.0.4) lib/magpie/endpoint.ex:1: Magpie.Endpoint.plug_builder_call/2
web_1  |         (magpie 2.0.4) lib/magpie/endpoint.ex:1: Magpie.Endpoint.call/2
web_1  |         (phoenix 1.6.7) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
web_1  |         (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

**Comment by x-ji** [comment]
Sorry, I think the dev environment was broken since it doesn't need to apply the plug. Applied a fix and pushed v2.0.6
