### ISSUE TITLE
Error following instructions for first time installation

### ISSUE THREAD

**Issue by luananama** [magpie-ea/magpie-backend#137]
Running `docker-compose up` gives the following error:
```
Starting magpie-backend_db_1 ... done
Starting magpie-backend_web_1 ... done
Attaching to magpie-backend_db_1, magpie-backend_web_1
db_1   |
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   |
db_1   | 2022-07-25 09:55:39.930 UTC [1] FATAL:  database files are incompatible with server
db_1   | 2022-07-25 09:55:39.930 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 13.7 (Debian 13.7-1.pgdg110+1).
magpie-backend_db_1 exited with code 1
web_1  | ** (Mix.Config.LoadError) could not load config config/config.exs
web_1  |     ** (CompileError) config/config.exs:6: module Config is not loaded and could not be found
web_1  |     (elixir) lib/code.ex:192: Code.eval_string/3
web_1  |     (mix) lib/mix/config.ex:188: Mix.Config.read!/2
magpie-backend_web_1 exited with code 1
```

**Comment by marcelklehr** [comment]
Resolved. Ah volume prune and a rebuild of the docker image was needed.
